# Generated by Django 5.2 on 2026-05-27 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionModel',
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notificacion_id",
                    models.CharField(db_index=True, max_length=36, unique=True),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("conflict", "Conflicto"),
                            ("confirmation", "Confirmacion"),
                            ("maintenance", "Alerta de mantenimiento"),
                            ("user_info", "Informacion de usuario"),
                        ],
                        max_length=32,
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("mensaje", models.TextField()),
                ("lectura_requerida", models.BooleanField(default=True)),
                ("es_leida", models.BooleanField(db_index=True, default=False)),
                (
                    "fecha_creacion",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("fecha_lectura", models.DateTimeField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                (
                    "usuario_destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones_recibidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificacion",
                "verbose_name_plural": "Notificaciones",
                "db_table": "notificaciones_notificacion",
                "ordering": ["-fecha_creacion"],
                "indexes": [
                    models.Index(
                        fields=["usuario_destino", "es_leida", "activo"],
                        name="notif_usuario_estado_idx",
                    )
                ],
            },
        ),
    ]
