# Generated by Django 5.2 on 2026-05-30 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notificaciones", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificacionmodel",
            name="activo",
            field=models.BooleanField(default=True, verbose_name="Activo"),
        ),
        migrations.AlterField(
            model_name="notificacionmodel",
            name="es_leida",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Leida"
            ),
        ),
        migrations.AlterField(
            model_name="notificacionmodel",
            name="lectura_requerida",
            field=models.BooleanField(default=True, verbose_name="Requiere lectura"),
        ),
        migrations.AlterField(
            model_name="notificacionmodel",
            name="mensaje",
            field=models.TextField(verbose_name="Mensaje"),
        ),
        migrations.AlterField(
            model_name="notificacionmodel",
            name="notificacion_id",
            field=models.CharField(
                db_index=True,
                max_length=36,
                unique=True,
                verbose_name="ID de notificacion",
            ),
        ),
        migrations.AlterField(
            model_name="notificacionmodel",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("asignacion_completada", "Asignacion completada"),
                    ("conflicto_detectado", "Conflicto detectado"),
                    ("reserva_confirmada", "Reserva confirmada"),
                    ("reserva_expirada", "Reserva expirada"),
                ],
                max_length=32,
                verbose_name="Tipo",
            ),
        ),
        migrations.AlterField(
            model_name="notificacionmodel",
            name="titulo",
            field=models.CharField(max_length=255, verbose_name="Titulo"),
        ),
        migrations.AlterField(
            model_name="notificacionmodel",
            name="usuario_destino",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notificaciones_recibidas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario destino",
            ),
        ),
    ]
