# Generated by Django 5.2 on 2026-05-28 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoParametroModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100, unique=True)),
                ('valor', models.JSONField(blank=True, default=dict)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'asignacion_catalogo_parametro',
            },
        ),
        migrations.CreateModel(
            name='ReglaNegocioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=100)),
                ('parametros', models.JSONField(blank=True, default=dict)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'asignacion_regla_negocio',
                'unique_together': {('tipo', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='AsignacionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(max_length=20)),
                ('estado', models.CharField(default='CONFIRMADO', max_length=50)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='academico.aulamodel')),
                ('bloque_horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='academico.horariobloquemodel')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='academico.grupomodel')),
            ],
            options={
                'db_table': 'asignacion_asignacion',
                'constraints': [models.UniqueConstraint(fields=('aula', 'bloque_horario', 'semestre'), name='uniq_aula_bloque_semestre')],
            },
        ),
    ]
