# Generated by Django 5.2 on 2026-05-28 00:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteTipoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('icono', models.CharField(help_text='Nombre de la clase CSS del icono (ej: fa-calendar-alt)', max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de Reporte',
                'verbose_name_plural': 'Tipos de Reportes',
            },
        ),
        migrations.CreateModel(
            name='ReporteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('GENERANDO', 'Generando'), ('COMPLETO', 'Completo'), ('FALLIDO', 'Fallido')], default='PENDIENTE', max_length=10)),
                ('datos_raw', models.JSONField(blank=True, null=True, verbose_name='Datos JSON crudos del reporte')),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('usuario_solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_solicitados', to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes_generados', to='reportes.reportetipomodel')),
            ],
            options={
                'verbose_name': 'Reporte Generado',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
