# Generated by Codex on 2026-05-29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reportes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportemodel",
            name="usuario_solicitante",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reportes_solicitados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
