# Generated by Django 5.2 on 2026-05-30 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_roles_usuario"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="permissionmodel",
            options={"verbose_name": "Permiso", "verbose_name_plural": "Permisos"},
        ),
        migrations.AlterModelOptions(
            name="rolemodel",
            options={"verbose_name": "Rol", "verbose_name_plural": "Roles"},
        ),
        migrations.AlterModelOptions(
            name="usuariomodel",
            options={"verbose_name": "Usuario", "verbose_name_plural": "Usuarios"},
        ),
        migrations.AlterField(
            model_name="permissionmodel",
            name="action",
            field=models.CharField(max_length=50, verbose_name="Accion"),
        ),
        migrations.AlterField(
            model_name="permissionmodel",
            name="description",
            field=models.TextField(blank=True, verbose_name="Descripcion"),
        ),
        migrations.AlterField(
            model_name="permissionmodel",
            name="resource",
            field=models.CharField(max_length=100, verbose_name="Recurso"),
        ),
        migrations.AlterField(
            model_name="rolemodel",
            name="code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("administrador", "Administrador"),
                    ("lider_sd", "Lider SD"),
                    ("auxiliar_sd", "Auxiliar SD"),
                    ("facultad", "Facultad"),
                    ("admisiones", "Admisiones"),
                ],
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Codigo",
            ),
        ),
        migrations.AlterField(
            model_name="rolemodel",
            name="description",
            field=models.TextField(blank=True, verbose_name="Descripcion"),
        ),
        migrations.AlterField(
            model_name="rolemodel",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="usuariomodel",
            name="cargo",
            field=models.CharField(blank=True, max_length=120, verbose_name="Cargo"),
        ),
        migrations.AlterField(
            model_name="usuariomodel",
            name="departamento",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Departamento"
            ),
        ),
        migrations.AlterField(
            model_name="usuariomodel",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usuarios",
                to="usuarios.rolemodel",
                verbose_name="Rol",
            ),
        ),
    ]
