# Generated by Django 5.2 on 2026-05-28 00:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("usuarios", "0002_roles_usuario"),
    ]

    operations = [
        migrations.CreateModel(
            name='AulaModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('capacidad', models.PositiveIntegerField()),
                ('tipo', models.CharField(max_length=100)),
                ('disponible', models.BooleanField(default=True)),
                ('restricciones', models.JSONField(blank=True, default=dict)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'academico_aula',
            },
        ),
        migrations.CreateModel(
            name='FacultadModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'academico_facultad',
            },
        ),
        migrations.CreateModel(
            name='HorarioBloqueModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dia', models.CharField(max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'academico_horario_bloque',
            },
        ),
        migrations.CreateModel(
            name='DocenteModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('disponibilidad', models.JSONField(blank=True, default=dict)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docentes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'academico_docente',
            },
        ),
        migrations.CreateModel(
            name='ProgramaModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas', to='academico.facultadmodel')),
            ],
            options={
                'db_table': 'academico_programa',
            },
        ),
        migrations.CreateModel(
            name='CursoModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('creditos', models.PositiveSmallIntegerField(default=3)),
                ('activo', models.BooleanField(default=True)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='academico.programamodel')),
            ],
            options={
                'db_table': 'academico_curso',
            },
        ),
        migrations.CreateModel(
            name='GrupoModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50)),
                ('num_estudiantes', models.PositiveIntegerField()),
                ('semestre', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='academico.cursomodel')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos', to='academico.docentemodel')),
            ],
            options={
                'db_table': 'academico_grupo',
                'unique_together': {('curso', 'codigo', 'semestre')},
            },
        ),
    ]
