# Generated by Django 5.2 on 2026-05-29 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoParametroModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(db_index=True, help_text='Identificador único del parámetro (snake_case).', max_length=120, unique=True)),
                ('valor', models.JSONField(help_text='Valor estructurado del parámetro. Puede ser string, número, lista o dict.')),
                ('grupo', models.CharField(choices=[('general', 'General'), ('asignacion', 'Asignación'), ('reservas', 'Reservas'), ('reportes', 'Reportes'), ('notificaciones', 'Notificaciones'), ('seguridad', 'Seguridad')], db_index=True, default='general', help_text='Agrupación lógica del parámetro.', max_length=50)),
                ('descripcion', models.TextField(blank=True, default='', help_text='Descripción del propósito del parámetro.')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el parámetro está vigente.')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parámetro del catálogo',
                'verbose_name_plural': 'Parámetros del catálogo',
                'db_table': 'parametros_catalogo',
                'ordering': ['grupo', 'clave'],
            },
        ),
    ]
