# Generated by Django 5.2 on 2026-05-30 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parametros", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="catalogoparametromodel",
            options={
                "ordering": ["grupo", "clave"],
                "verbose_name": "Parametro del catalogo",
                "verbose_name_plural": "Parametros del catalogo",
            },
        ),
        migrations.AlterField(
            model_name="catalogoparametromodel",
            name="activo",
            field=models.BooleanField(
                default=True,
                help_text="Indica si el parametro esta vigente.",
                verbose_name="Activo",
            ),
        ),
        migrations.AlterField(
            model_name="catalogoparametromodel",
            name="actualizado_en",
            field=models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
        ),
        migrations.AlterField(
            model_name="catalogoparametromodel",
            name="clave",
            field=models.CharField(
                db_index=True,
                help_text="Identificador unico del parametro (snake_case).",
                max_length=120,
                unique=True,
                verbose_name="Clave",
            ),
        ),
        migrations.AlterField(
            model_name="catalogoparametromodel",
            name="creado_en",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
        ),
        migrations.AlterField(
            model_name="catalogoparametromodel",
            name="descripcion",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Descripcion del proposito del parametro.",
                verbose_name="Descripcion",
            ),
        ),
        migrations.AlterField(
            model_name="catalogoparametromodel",
            name="grupo",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("asignacion", "Asignacion"),
                    ("reservas", "Reservas"),
                    ("reportes", "Reportes"),
                    ("notificaciones", "Notificaciones"),
                    ("seguridad", "Seguridad"),
                ],
                db_index=True,
                default="general",
                help_text="Agrupacion logica del parametro.",
                max_length=50,
                verbose_name="Grupo",
            ),
        ),
        migrations.AlterField(
            model_name="catalogoparametromodel",
            name="valor",
            field=models.JSONField(
                help_text="Valor estructurado del parametro. Puede ser string, numero, lista o dict.",
                verbose_name="Valor",
            ),
        ),
    ]
