# Generated by Django 5.2 on 2026-05-28 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserva_id', models.CharField(db_index=True, max_length=36, unique=True)),
                ('inicio', models.DateTimeField(db_index=True)),
                ('fin', models.DateTimeField(db_index=True)),
                ('estado', models.CharField(default='pending', max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='academico.aulamodel')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reservas_reserva',
                'indexes': [models.Index(fields=['aula', 'inicio', 'fin', 'estado'], name='reservas_re_aula_id_ec08ee_idx')],
            },
        ),
    ]
